version: '3.0'
volumes:
  postgres_volume:
    name: ${POSTGRES_VOLUME_NAME}
services:
  blazegraph:
    build:
      context: ./blazegraph-context
    hostname: blazegraph
    ports:
      - "${BLAZEGRAPH_PORT}:8080"
  # udviz:
  #   build:
  #     context: ./ud-viz-context
  #   ports:
  #     - ${UD_VIZ_PORT}:80