version: '3.0'
services:
  blazegraph:
    image: vcity/blazegraph-cors
    hostname: blazegraph
    ports:
      - "${BLAZEGRAPH_PORT}:8080" 
  udviz:
    build:
      context: ./udviz-context
    ports:
      - ${UD_VIZ_PORT}:8000