version: '3.0'
services:
  blazegraph:
    image: vcity/blazegraph-cors
    hostname: blazegraph
    ports:
      - "${BLAZEGRAPH_PORT}:8080" 
  # udviz:
  #   build:
  #     context: ./ud-viz-context
  #   ports:
  #     - ${UD_VIZ_PORT}:80