prefix geov: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/GeoVolumes/1.0/geovolumes/geovolumes#>
SELECT *
WHERE {
	?subject ?predicate ?object .
  		?object geov:bbox ?bbox.  		
  		?object geov:crs ?crs.
    	FILTER(?subject=<$URI> && ?predicate = geov:spatial)
}