prefix geov: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/GeoVolumes/1.0/geovolumes/geovolumes#>
SELECT *
WHERE {
  ?subject ?predicate ?object .
  filter(?subject=<$URI> && ?predicate = geov:children)
}